version: '2'
services:
  www:
    build: ./docker/www
    ports:
      - 8080:80
    volumes_from:
      - fpm
    links:
      - fpm
  fpm:
    build: ./
    volumes:
      - .:/var/www
    working_dir: /var/www
